services:
  gateway:
    build:
      context: .
      target: gateway
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_BASE_URL=http://backend:8081
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8081:8081"